repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.0b1
    hooks:
      - id: pylint
        verbose: true
        args:
          - --disable=unused-argument,missing-module-docstring,missing-function-docstring,missing-class-docstring,import-error,duplicate-code
          - --max-line-length=160
        entry: bash -c 'pylint "$@" | tee pylint.txt || true' --
        exclude: tests/conftest.py
