[tool.black]
line-length = 160

[tool.pycln]
all = true
exclude ="conftest.py$"

[tool.isort]
line_length = 160
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
